sample_alphabet: " 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
space_char: " "
samples: 100000
output_dir: ../../../data/line_chunks
chunk_size: 1024
overwrite: false
image_height: 32
image_width: 64
min_text_length: 4
max_text_length: 16
line_crops: true
word_count_min: 6
word_count_max: 18
word_length_min: 2
word_length_max: 8
crop_stride: 64
min_crop_text_length: 1
font_dir: ../fonts
font_extensions:
  - .ttf
  - .otf
  - .ttc
  - .otc
font_size_min: 24
font_size_max: 34
channels: 1
seed: 42
background_dir: ../backgrounds
background_extensions:
  - .png
  - .jpg
  - .jpeg
  - .bmp
  - .webp
horizontal_padding: 8
