# Set these two paths for the evaluation dataset or override them in CLI.
json: null
images: null

inference_config: ../inference/eng_101.yaml
checkpoint: null
out: ../../output/ocr_metrics.csv
device: cuda
batch_size: 64
limit: null
log_every: 100

parameters:
  scale_x: [-0.25, 0.25]
  y_pad: [-0.40, 0.50]
  x_pad: [0.0, 0.12]

optuna_trials: 200
optuna_metric: global_char_accuracy

optuna_trials_out: ../../output/ocr_trials.tsv
optuna_storage: sqlite:///../../output/ocr_optuna.db
optuna_study_name: eng_101_ocr_v1
optuna_progress: true
